apiVersion: apps/v1
kind: Deployment
metadata:
  name: av-separation-api
  namespace: av-separation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: av-separation
  template:
    metadata:
      labels:
        app: av-separation
    spec:
      containers:
      - name: av-separation
        image: av-separation:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "print('healthy')"
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: av-separation-service
  namespace: av-separation
spec:
  selector:
    app: av-separation
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: av-separation-hpa
  namespace: av-separation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: av-separation-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
