{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "av-separation-service",
    "namespace": "production",
    "annotations": {
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb",
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
    }
  },
  "spec": {
    "type": "LoadBalancer",
    "selector": {
      "app": "av-separation-transformer"
    },
    "ports": [
      {
        "name": "http",
        "port": 80,
        "targetPort": 8000,
        "protocol": "TCP"
      }
    ],
    "sessionAffinity": "ClientIP"
  }
}