apiVersion: apps/v1
kind: Deployment
metadata:
  name: av-separation-api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: av-separation-api
  template:
    metadata:
      labels:
        app: av-separation-api
    spec:
      containers:
      - name: api
        image: av-separation:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: av-separation-secrets
              key: database-url
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 2000m
            memory: 4Gi
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: av-separation-service
  namespace: production
spec:
  selector:
    app: av-separation-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
